In [1]:
%matplotlib inline
import pandas as pd
import fiona
import numpy as np
import geopandas as gpd

# Loading data

In [8]:
file_name = "../Data/KTC_AF_Benchmark_Research_for-publication-as-of-30-Nov-2018.xlsx"
xl_file = pd.ExcelFile(file_name)

In [9]:
df_cb = pd.read_excel(file_name, sheet_name='Overview')
df = pd.read_excel(file_name, sheet_name='1) Scoring', header=4)

In [12]:
df

,Company,Market Cap\nin US$ billion,Country,2016 company,Total\n2018,Rank 2018,Commitment,Supply Chain Standards,Management and Accountability,Training,...,Audit Disclosure,Unnamed: 32,Corrective Action Plans,Remedy Programs,Unnamed: 35,Rank 2016,Total\n2016,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,Adidas AG,47.360020,Germany,Yes,92.144429,1,100,100,100,100,...,100,95.0,100.0,100,100.00,1.0,81.0,NaN,NaN,NaN
1,Lululemon Athletica Inc.,10.588070,Canada,Yes,89.428886,2,100,80,100,100,...,80,90.0,100.0,75,87.50,3.0,69.0,NaN,NaN,NaN
2,Gap Inc.,12.925610,United States,Yes,74.737197,3,100,100,100,100,...,100,90.0,75.0,25,50.00,2.0,77.0,NaN,NaN,NaN
3,Primark (subsidiary retail group of Associated...,30.596620,United Kingdom,Yes,71.523555,4,100,100,100,100,...,80,85.0,75.0,50,62.50,5.0,63.0,NaN,NaN,NaN
4,Industria de Dise√±o Textil S.A.,111.820590,Spain,Yes,70.344819,5,100,90,100,100,...,80,90.0,75.0,25,50.00,6.0,61.0,NaN,NaN,NaN
5,PVH Corp.,11.930200,United States,Yes,69.091068,6,100,90,75,75,...,60,75.0,100.0,50,75.00,7.0,57.0,NaN,NaN,NaN
6,Hennes & Mauritz AB,7.918770,Sweden,Yes,64.862973,7,100,70,100,100,...,60,65.0,75.0,0,37.50,3.0,69.0,NaN,NaN,NaN
7,VF Corp.,22.633828,United States,Yes,63.787758,8,100,70,100,50,...,100,100.0,87.5,75,81.25,14.0,43.0,NaN,NaN,NaN
8,Nike Inc.,110.989890,United States,Yes,62.861572,9,100,100,75,75,...,50,70.0,100.0,50,75.00,10.0,49.0,NaN,NaN,
9,Hugo Boss AG,6.365040,Germany,Yes,61.969894,10,100,100,75,100,...,60,70.0,100.0,50,75.00,13.0,45.0,NaN,NaN,NaN
10,Puma SE,6.327950,Germany,No,61.394779,11,100,80,50,50,...,50,75.0,100.0,25,62.50,NaN,NaN,NaN,NaN,NaN
11,Ralph Lauren Corp.,9.290670,United States,Yes,57.502501,12,100,100,75,50,...,100,100.0,100.0,50,75.00,11.0,46.0,NaN,NaN,NaN
12,Burberry Group plc,9.299210,United Kingdom,No,54.202591,13,100,100,75,100,...,40,65.0,75.0,0,37.50,NaN,NaN,NaN,NaN,NaN
13,L Brands Inc.,14.138660,United States,Yes,52.132176,14,100,90,100,100,...,70,85.0,100.0,0,50.00,11.0,46.0,NaN,NaN,NaN
14,Hanesbrands Inc.,29.311140,United States,Yes,50.237297,15,100,80,100,75,...,80,80.0,75.0,100,87.50,8.0,54.0,NaN,NaN,NaN
15,Gildan Activewear Inc.,7.461250,Canada,Yes,46.989148,16,100,60,100,100,...,100,90.0,100.0,25,62.50,9.0,51.0,NaN,NaN,NaN
16,Kering S.A.,64.057030,France,Yes,44.541408,17,100,90,100,25,...,30,60.0,50.0,0,25.00,17.0,27.0,NaN,NaN,NaN
17,Walmart Inc.,315.789860,United States,No,44.059562,18,100,70,75,75,...,20,45.0,62.5,25,43.75,NaN,NaN,NaN,NaN,NaN
18,Under Armour Inc.,5.897590,United States,Yes,43.646729,21,100,90,50,50,...,40,65.0,50.0,25,37.50,15.0,38.0,NaN,NaN,NaN
19,Carter's Inc.,5.693000,United States,No,42.897079,19,100,70,50,75,...,80,85.0,75.0,0,37.50,NaN,NaN,NaN,NaN,NaN
20,Fast Retailing Co. Ltd.,45.446270,Japan,Yes,42.611022,19,100,60,50,75,...,40,65.0,100.0,25,62.50,15.0,38.0,NaN,NaN,NaN
21,Asics Corp.,3.120150,Japan,No,41.468794,22,100,70,50,75,...,50,70.0,50.0,0,25.00,NaN,NaN,NaN,NaN,NaN
22,Amazon.com Inc.,699.143520,United States,No,33.611222,23,100,70,25,50,...,0,40.0,75.0,0,37.50,NaN,NaN,NaN,NaN,NaN
23,Li & Fung Ltd.,4.321100,Hong Kong,No,32.617023,24,100,60,100,100,...,40,40.0,75.0,0,37.50,NaN,NaN,NaN,NaN,NaN
24,Columbia Sportswear Co.,5.217680,United States,No,30.666383,25,100,70,50,50,...,50,45.0,75.0,0,37.50,NaN,NaN,NaN,NaN,NaN
25,LPP Spolka Akcyjna,5.345460,Poland,No,27.735797,26,100,80,50,0,...,30,45.0,50.0,0,25.00,NaN,NaN,NaN,NaN,NaN
26,Michael Kors Holdings Ltd.,10.036400,United Kingdom,No,23.609222,27,50,70,0,50,...,10,30.0,75.0,0,37.50,NaN,NaN,NaN,NaN,NaN
27,Mr Price Group Ltd.,5.802980,South Africa,No,21.543809,28,100,60,50,75,...,0,5.0,37.5,0,18.75,NaN,NaN,NaN,NaN,NaN
28,Page Industries Ltd.,3.780950,India,No,19.464393,29,50,50,0,0,...,0,25.0,50.0,0,25.00,NaN,NaN,NaN,NaN,NaN
29,Herm√®s International S.A.,57.866450,France,No,17.004401,30,100,20,25,50,...,20,55.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN
30,LVMH Mo√´t Hennessy - Louis Vuitton SE,157.976810,France,No,13.752250,31,50,50,25,0,...,0,5.0,37.5,0,18.75,NaN,NaN,NaN,NaN,NaN
31,Salvatore Ferragamo S.p.A.,4.757780,Italy,No,13.395179,32,100,0,0,25,...,0,25.0,50.0,0,25.00,NaN,NaN,NaN,NaN,NaN
32,Foot Locker Inc.,5.957250,United States,No,11.537808,33,50,60,0,0,...,0,15.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN
33,Skechers USA Inc.,6.527400,United States,No,7.144429,34,50,0,0,25,...,20,35.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN
34,Pou Chen Corp.,3.959090,Taiwan,No,5.896679,35,50,0,25,25,...,0,5.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN
35,Prada S.p.A.,10.453260,Italy,Yes,5.001000,36,50,0,0,0,...,20,15.0,0.0,0,0.00,18.0,9.0,NaN,NaN,NaN
36,Anta Sports Products Ltd.,12.940660,China,No,3.536207,37,0,30,0,0,...,0,0.0,25.0,0,12.50,NaN,NaN,NaN,NaN,NaN
37,Shenzhou International Group Holdings Ltd.,15.520520,China,Yes,2.858572,38,50,0,0,0,...,0,0.0,0.0,0,0.00,19.0,1.0,NaN,NaN,NaN
38,Eclat Textile Corp. Ltd.,2.751480,Taiwan,No,1.430286,39,50,0,0,0,...,0,0.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN
39,Yue Yuen Industrial Holdings Ltd.,7.374190,Hong Kong,No,1.430286,39,50,0,0,0,...,0,0.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN
40,Shimamura Co. Ltd.,4.315690,Japan,No,0.000000,41,0,0,0,0,...,0,0.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN
41,Youngor Group Co. Ltd.,5.275620,China,No,0.000000,41,0,0,0,0,...,0,0.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN
42,Zhejiang Semir Garment Co. Ltd.,3.567260,China,No,0.000000,41,0,0,0,0,...,0,0.0,0.0,0,0.00,NaN,NaN,NaN,NaN,NaN

# Test if the searched company is in the database

In [24]:

testcom='H&M'
if testcom=='H&M':
    searchfor = ['Mauritz','H&M','H & M','Hennes & Mauritz']
    
df[df['Company'].str.contains('|'.join(searchfor))]

,Company,Market Cap\nin US$ billion,Country,2016 company,Total\n2018,Rank 2018,Commitment,Supply Chain Standards,Management and Accountability,Training,...,Audit Disclosure,Unnamed: 32,Corrective Action Plans,Remedy Programs,Unnamed: 35,Rank 2016,Total\n2016,Unnamed: 38,Unnamed: 39,Unnamed: 40
6,Hennes & Mauritz AB,7.91877,Sweden,Yes,64.862973,7,100,70,100,100,...,60,65.0,75.0,0,37.5,3.0,69.0,NaN,NaN,NaN

## Output global Index of the company

In [43]:
index=df[df['Company'].str.contains('|'.join(searchfor))]['Total\n2018']
index

6    64.862973
Name: Total\n2018, dtype: float64

In [44]:
file = open('../rating/rating_knowthechain.txt','w')
file.write(str(index))
file.close()